describe('The Home Page', () => {
  it('successfully loads', () => {
    cy.visit('/')
    cy.contains('Herzlich Willkommen!')
    cy.contains('Wiki').click()
    cy.contains('Willkommen im Wiki')
    cy.contains('Abc Modell')
    cy.get('.container > .d-flex > input').click({force: true}).type('Selbstwirksamkeit')
    cy.visit('/starkmacher')
    cy.contains('Anmelden')
    cy.contains('Anmelden').click()
    cy.contains('Neues Benutzerkonto erstellen').click()
    cy.contains('Erfolgreich angemeldet')
    cy.contains('Schließen').click()
    cy.contains('Sicherheitsnetz').click()
    cy.visit('/profil')
    cy.visit('/stimmungstagebuch')
    cy.contains('Hallo, wie geht\'s dir?')
  })
})
