describe('The Home Page', () => {
  it('successfully loads', () => {
    cy.viewport(550, 750)
    cy.visit('/')
    cy.contains('Herzlich Willkommen!')
    cy.get('.navbar-toggler-icon').click()
    cy.contains('Wiki').click()
    cy.get('.container > .d-flex > input').click({force: true}).type('A')
    cy.contains('Abc Modell')
    cy.contains('Alpen-Methode')
    cy.contains('Atemübung')
    cy.contains('Anmelden').click()
    cy.contains('Neues Benutzerkonto erstellen').click()
    cy.contains('Schließen').click()
    cy.contains('Stimmungstagebuch').click()
    cy.get('.navbar-toggler-icon').click()
    cy.get('.positive').click()
    cy.contains('Let\'s Go!').click()
  })
})
